### ISSUE TITLE
Upgrading to newer version, will it break HA compatibility?

### ISSUE THREAD

**Issue by Buster14** [myhomeiot/DahuaVTO#17]
So my Dahua VTO2202F-P-S2 suddenly stops working with the dmss apps, can't accept video call anymore.
And i was advised by the seller to update app version and firmware version.
What worries me is that they might lock HA compatibility as i have seen companies doing this to maintain exclusivity.
Has anyone upgraded to V4.511.0000000.0.R.220105?
Mine is currently 4.5 but i can use this integration, the only thing missing is the video call from dmss app, which seems to be difficult to emulate even with pbx...
Or is there any way downgrade it once it's updated?

**Comment by myhomeiot** [comment]
99% that HA lock will works after upgrade. Yes, you can downgrade your VTO in same way as you upgrade it, just make sure that you have your current version firmware downloaded. Unfortunately I can't test it because my VTO has only 16MB memory and last compatible firmware is 4.300.

Old firmware for your VTO you can found at this FTP: ftp.asm.cz in folder /Dahua/videovratni/VTO2202F/firmware/SIP_4.5_CZ/
In order to update firmware you should download and use [ConfigTool](https://www.dahuasecurity.com/ceen/support/downloadCenter/tools/MaintenanceTools?child=332), at Youtube you can find some videos about upgrading VTO's.

If you want to get answer from users which already upgraded to the latest firmware - ask this question in the [forum](https://community.home-assistant.io/t/dahua-vto-custom-integration), in the forum is more eye.
