### ISSUE TITLE
Adding more VTOs

### ISSUE THREAD

**Issue by DNA99** [myhomeiot/DahuaVTO#22]
Sorry im not familiar with YAML at all. How do I add an additional VTO?

**Comment by MooseGmaing** [comment]
Just copy the same config and modify the details:
`  - platform: dahua_vto
    name: Dahua VTH
    host: 192.168.1.41
    username: admin
    password: 123456
`

**Comment by MooseGmaing** [comment]
Just copy the config and modify the details:

- platform: dahua_vto
    name: Dahua VTO2
    host: `YOUR SECOND VTOs IP`
    username: `YOUR SECOND VTOs USERNAME`
    password: `YOUR SECOND VTOs PASSWORD`

GitHub makes the `-` symbol a dot, so replace the dot with `-` and you'll be fine.
Hope this helps

**Comment by DNA99** [comment]
Thanks for the reply. How about the unlock portion? How do I place the values there?

**Comment by myhomeiot** [comment]
@DNA99 In [unlock](https://github.com/myhomeiot/DahuaVTO#lock-example-with-call-to-open-door-service) you just need to specify `entity_id` of another VTO. If for new VTO you use name "Dahua VTO2" than you should have sensor `sensor.dahua_vto2`, so use it instead `entity_id: sensor.dahua_vto`. Sure you will need to create the new timer and change event listener where it's starts this timer.

In event [handler](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events) you will also get entity_id field in each event comes from VTOs, you can see all event fields in Home Assistant menu Developer Tools -> Events, just start listen for `dahua_vto` events.

If you you are new for YAML and it's look over complicated than you can try to use [this](https://github.com/rroller/dahua) integration. Personally I suggest to learn YAML configuration because it's will gives you much more possibilities in home automation.

**Comment by myhomeiot** [comment]
Hope my suggestions helps. Feel free to add comments here even I close the issue.
