### ISSUE TITLE
Camera Feed Automation

### ISSUE THREAD

**Issue by MooseGmaing** [myhomeiot/DahuaVTO#26]
Hi,

I've read the documentation and examples on this repo, but I still don't understand how to access the VTO status (BackKeyLight States). I have this sensor called `sensor.dahua_vto`, but its status is just `OK`, and it never changes. I need the VTO status because I'm replacing one of my Dahua VTHs with a tablet running Home Assistant. I'd like this to automatically switch to the VTO's camera feed when someone rings (just like it does on the VTH). If there'd be some way to make a sensor similar to  `sensor.dahua_vto` whose status corresponds to the BackKeyLight States, I could use that to trigger my automation.

Thanks

**Comment by myhomeiot** [comment]
The sensor `sensor.dahua_vto` shows only the state of communication with VTO, `OK` means that you configure everything correctly and you have connection to your VTO. Now you can use automation example from [readme](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events) in order to receive events from VTO like doorbell, etc.
If you are not familiar with Home Assistant YAML configuration, than you can use [this](https://github.com/rroller/dahua) integration which work similar but has dedicated sensor object for doorbell.

**Comment by MooseGmaing** [comment]
Oh, ok, thanks very much, and sorry for bothering you. I'll set that up in that case. I'm only worried that you helped me a couple of months ago and gave me some YAML that let me press a button to unlock my gate (controlled by the VTO). I hope that'll be supported on that integration (it should because they have a service for that).

**Comment by myhomeiot** [comment]
You can also look for some configuration examples and discussions in this [thread](https://community.home-assistant.io/u/Archer4499), maybe you will get some interesting ideas for implementation.

**Comment by myhomeiot** [comment]
@MooseGmaing Great! Thanks for update.
