### ISSUE TITLE
is VTO2201 supported?

### ISSUE THREAD

**Issue by juagicre** [myhomeiot/DahuaVTO#34]
I see the list and even the numbers are very similar, it seems I don't have a supported VTO for this integration... 
As the title describes I have the VTO2201. I guess API will be much the same with most of the ones that are listed.

I would like to give it a try but I feel a bit lost using HACS at the moment, I could download the addon but I don't see a way to run, configure or stop it like I used to see... is there something changed I did not realize all this time I did not use this part of HA? Should I create a new file to configure the intercom configuration? If so, what name and where exactly?

Thanks for all clarifications and I hope i'm useful to give some positive feedback about a new device supported :)

**Comment by myhomeiot** [comment]
Hello, if you are not really familiar with HA yaml configuration, you can try to use [this](https://github.com/rroller/dahua) integration, it's should fit all your needs.

**Comment by myhomeiot** [comment]
Great! In this case you shouldn't have a problems with yaml configuration from readme! VTO2201 should works just fine.
This integration fits all your needs, the rroller integration better for newbie's because has GUI setup and all sensors as sensors, this integration provide only any messaging from/to VTO/VTH and all sensors users creating for their needs using regular Home Assistant template sensors. rroller integration also support Dahua cameras and DVR/XVRs.

Start configuration from [platform](https://github.com/myhomeiot/DahuaVTO?tab=readme-ov-file#configuration-examples) and [Dahua VTO All Events](https://github.com/myhomeiot/DahuaVTO?tab=readme-ov-file#automation-example-with-doorbell-ring-and-unlock-events) automation, when your start getting events when you can continue to configure bell button and door open from examples. Many examples you can find also in the [forum](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693) where you can also ask questions.

**Comment by myhomeiot** [comment]
@juagicre Do you get VTO2201 worked?

**Comment by myhomeiot** [comment]
I will close this issue, if you will have similar questions in the future you can ask it on [forum](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693) or maybe you will find ready samples of sensors on previous user conversations.

Happy New Year!
